### ISSUE TITLE
会場決め

### ISSUE THREAD

**Issue by arayaryoma** [kosen10s/event-todo#17]
候補 yahoo lodge

**Comment by ysakasin** [comment]
@Allajah 
> イベント申請は1カ月前までに行ってください。審査に1～2週間いただきますので、あらかじめご了承ください。

https://lodge.yahoo.co.jp/event_pc.html

**Comment by arayaryoma** [comment]
直接足を運ばなきゃいけなくて無理だった

**Comment by arayaryoma** [comment]
http://www.its-kenpo.or.jp/fuzoku/kaigi/index.html
IT健保会議室安い。Wi-Fiがある部屋とない部屋があるとの情報あり
https://www.wantedly.com/companies/altplus/post_articles/101779

**Comment by arayaryoma** [comment]
HDMIがない可能性あり

**Comment by arayaryoma** [comment]
https://spacemarket.com/spaces/utnakameguro/rooms/L4iCz7UnYkcNe7r4
